language: minimal
dist: bionic

script:
  - echo "So long, and thanks for all the fish." > my.artifact

deploy:
  provider: releases
  api_key: $GITHUB_APIKEY
  file:
    - my.artifact
  skip_cleanup: true
  on:
    tags: true

