language: minimal
dist: bionic

script:
  - echo "So long, and thanks for all the fish!" > artifact.txt

before_deploy:
  - |
    if [[ "${TRAVIS_TAG}" = "" ]]; then
      git config --local user.name "${GITHUB_USER}"
      git config --local user.email "${GITHUB_EMAIL}"
      export TRAVIS_TAG=unstable
      curl -XDELETE --header "Authorization: token $GITHUB_APIKEY" "https://api.github.com/repos/${TRAVIS_REPO_SLUG}/git/refs/tags/${TRAVIS_TAG}" || true
      git tag -d "${TRAVIS_TAG}" || true
      git tag "${TRAVIS_TAG}"
    fi

deploy:
  provider: releases
  api_key: $GITHUB_APIKEY
  file:
    - artifact.txt
  skip_cleanup: true
  overwrite: true
  on:
    branch: $TRAVIS_BRANCH

branches:
  except:
  - unstable
